title: SITE_TITLE
description: SITE_DESCRIPTION
author:
  name: AUTHOR_NAME
  email: EMAIL@EXAMPLE.COM
  twitter: TWITTER_ID
copyright_year: YEAR
sass:
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
