title: SITE_TITLE
description: SITE_DESCRIPTION
author:
  name: AUTHOR_NAME
  email: EMAIL@EXAMPLE.COM
copyright_year: YEAR
google_analytics: UA-000000000-0
aladin_ttbkey: TTB_KEY_VALUE
mathjax: enable #enable/disable
sass:
  style: compressed
remote_theme: paikwiki/jekyll-theme-paikblog@main
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-remote-theme
